definitions:
  handlers.AuthRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.Item:
    type: object
  models.ItemDTO:
    properties:
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
    type: object
info:
  contact: {}
  title: Go JWT API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Register
      tags:
      - Auth
  /items:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ItemDTO'
            type: array
      security:
      - BearerAuth: []
      summary: Get items
      tags:
      - Item
    post:
      consumes:
      - application/json
      parameters:
      - description: Item
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
      security:
      - BearerAuth: []
      summary: Create item
      tags:
      - Item
  /items/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Item
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ItemDTO'
            type: array
      security:
      - BearerAuth: []
      summary: Update item
      tags:
      - Item
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
